function instructionsSegmentationVisualizer()

% Make a figure for the instructions.
instructionsPlot = figure('Name','Instruction on how to use the ''Segmentation Visualizer''.','NumberTitle','Off','Color','white','Units','Normalized','Position',[0.27 0.15 0.53 0.7],'Menubar','None','Toolbar','None','Resize','off');

% Create the message that is being displayed.
msg = {'\bf\fontsize{15}Instructions on how to use the segmentation visualizer:\rm\fontsize{12} ',...
    '\bf\fontsize{10}\color{red}ALWAYS APPLY STEP 1 BEFORE CHANGING STEP 2. IF NOT, THE RESULTS WILL NOT BE SAVED. ',...
    '\bf\fontsize{10}\color{red}THE RESULTS ARE ONLY SAVED AFTER CLICKING APPLY CHANGES AND THEN CLOSING THE VISUALIZER.\rm\fontsize{12} ',...
    '\bf\fontsize{12}\color{black}Step 1 - Segment the masks correctly:'...
    '\rm\fontsize{10}  1.1. For every data set, set the parameters that look good to you so you capture the object(s) nicely.',...
    '\rm\fontsize{9}         a) Put the circularity to 1 & object size to 0. This will show all the objects being segmented without additional filters.',...
    '\rm\fontsize{9}         b) Change the contrast between 0 - 0.1 (low: breaks up objects - high: joins objects).',...
    '\rm\fontsize{9}           -> The update will automatically change to the actually used value (which might be different from the set value).',...
    '\rm\fontsize{9}              Just play around a little with it.',...
    '\rm\fontsize{9}         c) To increase calculation speed in subsequent steps, filter such that only few objects are visible (gray or white).\rm\fontsize{6} ',...
    ' ',...
    '\rm\fontsize{10}  1.2. Navigate between the different images by clicking the slider on top.',...
    '\rm\fontsize{9}         a) This will not forget the previously set settings for the other data sets.',...
    '\rm\fontsize{9}         b) This does NOT apply the settings just yet. These changes are TEMPORARY.\rm\fontsize{6} ',...
    ' ',...
    '\rm\fontsize{10}  1.3.1. Click the ''Apply to current data mask'' button to update a SINGLE data set (the one currently shown).',...
    '\rm\fontsize{9}         a) This will update the ''Selected axon(s)'' and ''Final segments'' images of the CURRENT data set.',...
    '\rm\fontsize{10}  1.3.2. Click the ''Apply to all data masks'' button to update all data sets.',...
    '\rm\fontsize{9}         a) This will update the ''Selected axon(s)'' and ''Final segments'' images of all data set.',...
    '\rm\fontsize{9}         b) To speed up calculations, only the data sets with changed settings are recalculated.\rm\fontsize{6} ',...
    ' ',...
    '\bf\fontsize{12}Step 2 - Change the segments settings:',...
    '\rm\fontsize{9}\color{red}All changes here are TEMPORARILY applied to ALL data sets to ensure they are all treated equally.',...
    '\rm\fontsize{9}Not clicking ''Apply to data segments'' or ''Apply to all data segments'' does NOT actually save the changes.\rm\fontsize{6} ',...
    ' ',...
    '\rm\fontsize{10}\color{black}  2.1. Check the settings for the pixelsize.',...
    '\rm\fontsize{9}         a) These will (most likely) be the same for all.',...
    '\rm\fontsize{9}         b) The default parameters are the ONI microscopy pixelsize (0.117 µm) and the chosen rendering pixel size (0.003 µm).\rm\fontsize{6} ',...
    ' ',...
    '\rm\fontsize{10}  2.2. Check the settings for the segments and axon mask width parameters.',...
    '\rm\fontsize{9}         a) These should be the same for all to ensure equal treatment. It is hard coded to be that way.',...
    '\rm\fontsize{9}         b) The default parameters settings are pretty good.',...
    '\rm\fontsize{9}           -> Increasing mask dilation might add off-axon signal.',...
    '\rm\fontsize{9}           -> Play around with the segment length and width in case you feel like.',...
    '\rm\fontsize{9}           -> Increase ''Segment distance'' to decrease overlap between segments if needed.\rm\fontsize{6} ',...
    };

% Display the message in the figure.
annotation(instructionsPlot,'TextBox',[0.05,0.05,0.9,0.9],'String',msg,'HorizontalAlignment','left','FontUnits','Normalized','FontSize',0.025,'FontWeight','bold','EdgeColor','none')