function instructionsEndpointSegmentation()

% Make a figure for the instructions.
instructionsEndpoints = figure('Name','Instruction on how to use the ''Mask by endpoint selection.''.','NumberTitle','Off','Color','white','Units','Normalized','Position',[0.27 0.15 0.53 0.7],'Menubar','None','Toolbar','None','Resize','off');

% Create the message that is being displayed.
msg = {'\bf\fontsize{15}Instructions on how to use the ''Create mask by endpoint selection'':\rm\fontsize{12} ',...
    '\bf\fontsize{10}Note that this mode is only available when a single data set is selected.\rm\fontsize{12} ',...
    ' ',...
    '\bf\fontsize{10}\color{red}ALWAYS APPLY THE GENERAL INSTRUCTION BEFORE. IT IS IMPORTANT HERE TO GET THE RIGHT OBJECTS IN THE IMAGE BEFOREHAND.',...
    '\bf\fontsize{10}IF NOT DONE WELL, THIS STEP WILL NOT PROVIDE THE ANTICIPATED RESULTS.\rm\fontsize{12} ',...
    ' ',...
    '\bf\fontsize{12}\color{black}Step 1 - Segment the mask correctly:',...
    '\rm\fontsize{10}  1.1. See other instructions.\rm\fontsize{6} ',...
    ' ',...
    '\rm\fontsize{10}  1.2. Make sure that the ''Num. objects'' setting is set to the number of objects that contain axons (by visual inspection).',...
    '\rm\fontsize{9}         a) This can be checked by inspecting the \bfwhite \rmobjects, rather than the \bfgray \rmones.\rm\fontsize{6} ',...
    ' ',...
    '\rm\fontsize{10}  1.3. Apply all the changes to the data mask(s) by clicking the ''Apply to current data mask'' button.\rm\fontsize{6} ',...
    ' ',...
    '\bf\fontsize{12}Step 2 - Select the desired endpoints to create the axon path(s):'...
    '\rm\fontsize{10}  2.1. Click the ''Mask by endpoint selection'' button.\rm\fontsize{6} ',...
    ' ',...
    '\rm\fontsize{10}  2.2. Click the confirmation dialog that you have changed the mask to the right settings AND clicked apply.',...
    '\rm\fontsize{9}         a) Double check that the mask is a suitable mask.',...
    '\rm\fontsize{9}         b) Click confirm.\rm\fontsize{6} ',...
    ' ',...
    '\rm\fontsize{10}  2.3. The endpoints will be visualized in a new plot and an identifier will be displayed if you click on a point.',...
    '\rm\fontsize{9}         a) An input dialog will open where you can write the identifiers of the axon start and end.',...
    '\rm\fontsize{9}           -> This is compatible with multiple axons within a single object.',...
    '\rm\fontsize{9}           -> Correct format:    e.g., [Start1 End1]',...
    '\rm\fontsize{9}                                                   [Start1 End1;Start2 End2;Start3 End3]',...
    '\rm\fontsize{9}         b) The same number of input dialogs will open as the ''Num. objects parameter''.',...
    '\rm\fontsize{9}         c) Setting the input dialog to [0 0] will remove that object from consideration.\rm\fontsize{6} ',...
    ' ',...
    '\rm\fontsize{10}  2.4. The changes will automatically be applied to the data set.',...
    '\rm\fontsize{9}         a) Do NOT click ''Apply to current data mask''',...
    '\rm\fontsize{9}         b) To ensure that the axons were correctly selected, check the ''Selected axon(s)'' plot.',...
    '\rm\fontsize{9}         b) Close the Segmentation Visualizer to save the final data into the data browser.\rm\fontsize{6} ',...
    ' ',...
    '\bf\fontsize{10}\color{red}ANY CHANGES YOU MAKE TO THE MASK SETTINGS WILL REMOVE THE ''MASK BY ENDPOINT SELECTION'' RESULTS.',...
    };

% Display the message in the figure.
annotation(instructionsEndpoints,'TextBox',[0.05,0.075,0.9,0.9],'String',msg,'HorizontalAlignment','left','FontUnits','Normalized','FontSize',0.025,'FontWeight','bold','EdgeColor','none')